{% set name = "wsidicom" %}
{% set version = "0.22.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wsidicom-{{ version }}.tar.gz
  sha256: 576b352369171a535faff957cbaa8aa58368ddc1f564dddba175df2fd44085df

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry
    - _python_rc
  run:
    - numpy >=1.22.0,<2.0.0
    - pillow >=9.1.1,<10.0.0
    - pydicom >=3.0.0
    - python >={{ python_min }},<4.0
    - poetry
    - dicomweb-client >=0.59.1
    - six
    - marshmallow >=3.20.1
    - universal_pathlib >=0.2.1
    - _python_rc

test:
  imports:
    - wsidicom
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/imi-bigpicture/wsidicom
  summary: Tools for handling DICOM based whole scan images
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
