{% set name = "wsidicom" %}
{% set version = "0.35.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/wsidicom-{{ version }}.tar.gz
  sha256: 513b347614505c3356bd4316a53bf05ede6f9e2b7d5780b58565540682afae95

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry
    - hatchling
  run:
    - numpy >=1.22.0
    - pillow >=9.1.1
    - pydicom >=3.0.0
    - python >={{ python_min }}
    - poetry
    - dicomweb-client >=0.61.0
    - fsspec >=2024.2.0
    - six
    - marshmallow >=4.0.0
    - universal_pathlib >=0.3.0
    - imagecodecs >=2024.1.1,!=2024.9.22
    - cachetools >=7.1.3
    - pylibjpeg-rle >=2.0.0,<3.0.0
    - pyjpegls >=1.2.0,<2.0.0
    - pylibjpeg-openjpeg >=2.1.1,<3.0.0
    - opencv >=4.5.0

test:
  imports:
    - wsidicom
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/imi-bigpicture/wsidicom
  summary: Tools for handling DICOM based whole scan images
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
