{% set name = "wsidicom" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wsidicom-{{ version }}.tar.gz
  sha256: 6c508ff2ce106e0958573e49852fcca09d32599983a8199ff6e032e9ce7fcaef

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - poetry
  run:
    - numpy >=1.15.0,<2.0.0
    - pillow >=9.0.0,<10.0.0
    - pydicom >=2.1.0,<3.0.0
    - python >=3.6,<4.0
    - poetry
    - dicomweb-client
    - six

test:
  imports:
    - wsidicom
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/imi-bigpicture/wsidicom
  summary: Tools for handling DICOM based whole scan images
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
