{% set name = "wsidicom" %}
{% set version = "0.26.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wsidicom-{{ version }}.tar.gz
  sha256: 45435b6ed2e3947f453653bc777491ad050afc1ca9166b66cad8823855042a63

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry
  run:
    - numpy >=1.22.0
    - pillow >=9.1.1
    - pydicom >=3.0.0
    - python >={{ python_min }}
    - poetry
    - dicomweb-client >=0.59.2
    - fsspec >=2024.2.0,<2025.0.0
    - six
    - marshmallow >=3.20.1,<4
    - universal_pathlib >=0.2.1
    - imagecodecs >=2024.1.1,!=2024.9.22

test:
  imports:
    - wsidicom
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/imi-bigpicture/wsidicom
  summary: Tools for handling DICOM based whole scan images
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
