{% set name = "wsidicom" %}
{% set version = "0.19.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wsidicom-{{ version }}.tar.gz
  sha256: 393ef4e99c0b727d6120c2928af0ed2b5ee5bb3213d89fb509e52df0887d3907

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6,<4.0
    - poetry
  run:
    - numpy >=1.22.0,<2.0.0
    - pillow >=9.1.1,<10.0.0
    - pydicom >=2.1.0,<3.0.0
    - python >=3.6,<4.0
    - poetry
    - dicomweb-client >=0.59.1
    - six
    - marshmallow >=3.20.1

test:
  imports:
    - wsidicom
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/imi-bigpicture/wsidicom
  summary: Tools for handling DICOM based whole scan images
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
